=== hdezroberto00/lnd-2122-roberto/tema6-xml-schema(xsd)/u6_a2_aeropuerto/airport_roberto.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="aeropuerto">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="nombre" type="xs:string"/>
				<xs:element name="fecha" type="xs:date"/>
				<xs:element name="vuelo" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="origen" type="xs:string"/>
							<xs:element name="destino" type="xs:string"/>
							<xs:element name="hora-salida" type="xs:time"/>
							<xs:element name="hora-llegada" type="xs:time"/>
						</xs:sequence>
						<xs:attribute name="codigo" type="xs:ID" use="required"/>
						<xs:attribute name="estado">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="[C,E,R]"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== hdezroberto00/lnd-2122-roberto/tema6-xml-schema(xsd)/u6_a2_aeropuerto/airport_roberto.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Tue Mar 22 12:31:18 WET 2022 -->

<aeropuerto xsi:noNamespaceSchemaLocation="airport_roberto.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<nombre>Tenerife Notre-Los Rodeos</nombre>
	<fecha>2017-05-04</fecha>
	<vuelo codigo="UX5103" estado="E">
		<origen>Tenerife</origen>
		<destino>Sevilla</destino>
		<hora-salida>16:00:00</hora-salida>
		<hora-llegada>19:15:00</hora-llegada>
	</vuelo>
	
	<vuelo codigo="IB2015" estado="R">
		<origen>Tenerife Norte</origen>
		<destino>Madrid</destino>
		<hora-salida>18:00:00</hora-salida>
		<hora-llegada>21:15:00</hora-llegada>
	</vuelo>
</aeropuerto>
