=== hdezroberto00/lnd-2122-roberto/tema6-xml-schema(xsd)/u6_a3_veterinaria/veterinaria.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="clinicaveterinariaroberto">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="cliente" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nombre" type="xs:string"/>
							<xs:element name="apellido" type="xs:string" minOccurs="0"/>
							<xs:element name="animales" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:choice maxOccurs="unbounded">
										<xs:element name="gato" type="datosanimal"/>
										<xs:element name="perro" type="datosanimal"/>
										<xs:element name="reptil" type="datosanimal"/>
									</xs:choice>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="codigo" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="datosanimal">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="edad">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0"/>
						<xs:maxInclusive value="15"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="raza">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="5"/>
						<xs:maxLength value="15"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="sexo" default="M">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[M,H]"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== hdezroberto00/lnd-2122-roberto/tema6-xml-schema(xsd)/u6_a3_veterinaria/veterinaria.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- New document created with EditiX at Tue Mar 29 11:28:49 WEST 2022 -->

<clinicaveterinariaroberto xsi:noNamespaceSchemaLocation="/home/malu/Escritorio/veterinaria/veterinaria.xsd" codigo="vet1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<cliente>
		<nombre>Roberto</nombre>
		<animales>
			<gato sexo="M">
				<nombre>Cocos</nombre>
				<edad>7</edad>
				<raza>Persa</raza>
			</gato>
		</animales>
	</cliente>
	<cliente>
		<nombre>Diego</nombre>
		<apellido>Rolando</apellido>
		<animales>
			<reptil sexo="H">
				<nombre>Lagarto</nombre>
				<edad>3</edad>
				<raza>Iguana</raza>
			</reptil>
		</animales>
	</cliente>
</clinicaveterinariaroberto>
